version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: fintech_redis
    ports:
      - '6379:6379'
  mongodb:
    image: mongo:6.0
    container_name: fintech_mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: fintech_logs
    volumes:
      - mongodb_data:/data/db
  postgres:
    image: postgres:15
    container_name: fintech_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fintech_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  mongodb_data: